# Generated by CMake 2.8.7

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target gdcmCommon
ADD_LIBRARY(gdcmCommon SHARED IMPORTED)

# Create imported target gdcmDICT
ADD_LIBRARY(gdcmDICT SHARED IMPORTED)

# Create imported target gdcmDSED
ADD_LIBRARY(gdcmDSED SHARED IMPORTED)

# Create imported target gdcmIOD
ADD_LIBRARY(gdcmIOD SHARED IMPORTED)

# Create imported target gdcmMSFF
ADD_LIBRARY(gdcmMSFF SHARED IMPORTED)

# Create imported target gdcmMEXD
ADD_LIBRARY(gdcmMEXD SHARED IMPORTED)

# Create imported target gdcmjpeg8
ADD_LIBRARY(gdcmjpeg8 SHARED IMPORTED)

# Create imported target gdcmjpeg12
ADD_LIBRARY(gdcmjpeg12 SHARED IMPORTED)

# Create imported target gdcmjpeg16
ADD_LIBRARY(gdcmjpeg16 SHARED IMPORTED)

# Create imported target gdcmexpat
ADD_LIBRARY(gdcmexpat SHARED IMPORTED)

# Create imported target gdcmopenjpeg
ADD_LIBRARY(gdcmopenjpeg SHARED IMPORTED)

# Create imported target gdcmcharls
ADD_LIBRARY(gdcmcharls SHARED IMPORTED)

# Create imported target gdcmmd5
ADD_LIBRARY(gdcmmd5 SHARED IMPORTED)

# Create imported target gdcmzlib
ADD_LIBRARY(gdcmzlib SHARED IMPORTED)

# Create imported target socketxx
ADD_LIBRARY(socketxx SHARED IMPORTED)

# Load information for each installed configuration.
GET_FILENAME_COMPONENT(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
FILE(GLOB CONFIG_FILES "${_DIR}/GDCMTargets-*.cmake")
FOREACH(f ${CONFIG_FILES})
  INCLUDE(${f})
ENDFOREACH(f)

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
